### ISSUE TITLE
sizeof用の分岐でブロック分が使用されている意図をしりたいです

### ISSUE THREAD

**Issue by tychy** [tychy/hooligan#140]
@yokonao 
https://github.com/tychy/hooligan/blob/12e2a92b54772668f6d7d67cbaab0ab06e36bbe2/parser.c#L198-L218

209行目でブロック文を使っているのはなにか意図がありますか？

**Comment by yokonao** [comment]
さすがにないと思いたい...
もともとif文があって、{}だけ消し忘れた説を推します。

**Comment by yokonao** [comment]
@tychy
