### ISSUE TITLE
可変長引数をとる関数を定義可能にする

### ISSUE THREAD

**Issue by yokonao** [tychy/hooligan#146]
定義済みの関数を呼び出すことはできる（printf等）
しかしユーザー定義の関数は可変長引数をとれない

errorやprintlnなど可変長引数をとる関数をコンパイルするために必要な機能
おそらくセルフホスト前最後の課題

**Comment by tychy** [comment]
errorを自前で実装し直して当面回避しています。

**Comment by yokonao** [comment]
難しいらしいのでセルフホストまではスルーします。
